### PR TITLE
default to mockStorage if localstorage doesn't exist

### PR DESCRIPTION
**Pull request by Mateiadrielrafael**
Solving #23

### CODE REVIEW

**Comment by martinsik** [comment]
Hey @Mateiadrielrafael, Thanks! Could you just please remove `package-lock.json` from the commit?

**Comment by Mateiadrielrafael** [comment]
Im only know the basic git commands. Will a git rm do?

**Comment by Mateiadrielrafael** [comment]
I only know the basic git commands. Will git rm do the job or do i need to do something more advanced? @martinsik

**Comment by Mateiadrielrafael** [comment]
@martinsik so?

**Comment by martinsik** [comment]
Have a look at this https://help.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history and this https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

**Pull request closed without merging**
